version: '3.1'

services:
  messages:
    build: ./message_service/
#    ports: 
#      - "8000:8000"
    volumes: 
      - "./message_service:/app"
    environment: 
      db_username: postgres 
      db_password: example
      db_name: postgres 

  auth:
    build: ./login_service/
#    ports:
#      - "3000:3000"
    volumes: 
      - "./login_service:/app"

  db:
    image: postgres
    restart: always
#    ports:
#      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example

  web:
    image: nginx
    ports:
      - "80:80"
    volumes: 
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - NGINX_POST=80

      
