version: '3.1'

services:

  ui:
    build: ./ui-service/
    volumes: 
      - ./ui-service:/app
      - frontend:/app/dist/
    command: "yarn build"

  messages:
    build: ./message_service/
#    volumes: 
#      - "./message_service:/app"
    environment: 
      db_username: postgres 
      db_password: example
      db_name: postgres 
    depends_on:
      - db
      - broker

  auth:
    build: ./auth_service/
#    volumes: 
#      - ./auth_service:/app
    depends_on:
      - broker
    environment:
      address: :3000
      broker_addr: broker:6379
      secret_key: secret


  web:
    image: nginx
    ports:
      - "80:80"
    volumes: 
      - ./configs/nginx.conf:/etc/nginx/nginx.conf
      - frontend:/etc/nginx/html/ 
    environment:
      - NGINX_POST=80

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  broker:
    image: redis
    restart: always
    volumes: 
      - ./configs/redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf

  

volumes: 
  frontend:
