version: '3.1'

services:
  messages:
    build: ./message_service/
    volumes: 
      - "./message_service:/app"
    environment: 
      db_username: postgres 
      db_password: example
      db_name: postgres 
    depends_on:
      - db
      - broker

  auth:
    build: ./login_service/
    volumes: 
      - ./login_service:/app
    depends_on:
      - broker

  web:
    image: nginx
    ports:
      - "80:80"
    volumes: 
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - NGINX_POST=80

  db:
    image: postgres
    restart: always
#    ports:
#      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example

  broker:
    image: redis
    restart: always
    volumes: 
      - ./conf/redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf

  

      
