version: '3.1'

services:
  messages:
    build: ./message_service/
    volumes: 
      - "./message_service:/app"
    environment: 
      db_username: postgres 
      db_password: example
      db_name: postgres 
    depends_on:
      - db
      - broker

  auth:
    build: ./auth_service/
    volumes: 
      - ./login_service:/app
    depends_on:
      - broker
    environment:
      - address: :3000
      - broker_addr: broker:6379
      - secret_key: secret


  web:
    image: nginx
    ports:
      - "80:80"
    volumes: 
      - ./configs/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - NGINX_POST=80

  db:
    image: postgres
    restart: always
#    ports:
#      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example

  broker:
    image: redis
    restart: always
    volumes: 
      - ./configs/redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf

  

      
